### PR TITLE
fix broken VRBangers network

### LINKED ISSUE #590: VRBangers scraper does not show updates after 17 sep 2021
VRBangers scraper does not show updates after 17 sep 2021

goto
https://vrbangers.com/
select latest videos

4 updates missing so far

### PR DESCRIPTION
**Pull request by theRealKLH**
Fixes #590 major code change to website

### CODE REVIEW

File: pkg/scrape/vrbangers.go [hunk 1]
```diff
@@ -28,27 +30,47 @@ func VRBangersSite(wg *sync.WaitGroup, updateSite bool, knownScenes []string, ou
...
+		//if not valid scene...
+		if gjson.Get(JsonMetadata, "status.message").String() != "Ok" {
 			return
 		}
-		// Scene ID - get from URL
-		sc.SiteID = strings.Split(e.ChildAttr(`link[rel=shortlink]`, "href"), "?p=")[1]
+
+		//Scene ID - back 8 of the"id" via api response
+		sc.SiteID = strings.TrimSpace(gjson.Get(JsonMetadata, "data.item.id").String()[16:])
 		sc.SceneID = slugify.Slugify(sc.Site) + "-" + sc.SiteID
```
Comment (alexnsfw) [inline pkg/scrape/vrbangers.go:47]: Since scene IDs are changing, force updating scenes will duplicate all existing scenes. Also some urls have changed<sup>1</sup>, so those will be duplicated even without force updating. Should there be a migration?

<sup>1</sup> Changed slugs:
```
ayumis-first-time-2 -> ayumis-first-time
caught_watching -> caught-watching
downward_slut -> downward-slut
```

File: pkg/scrape/vrbangers.go [hunk 2]
```diff
@@ -111,36 +106,37 @@ func VRBangersSite(wg *sync.WaitGroup, updateSite bool, knownScenes []string, ou
...
-		url := strings.Split(e.Attr("href"), "?")[0]
-		pageURL := e.Request.AbsoluteURL(url)
+		//url := strings.Split(e.Attr("href"), "?")[0]
+		pageURL := e.Request.AbsoluteURL(e.Attr("href"))
 
 		siteCollector.Visit(pageURL)
 	})
 
-	siteCollector.Visit(URL)
+	siteCollector.Visit(URL + "?sort=latest")
```
Comment (alexnsfw) [inline pkg/scrape/vrbangers.go:139]: A few scenes (_As Thick As Thieves_, _Bachelor No More_ & _Sorority Hookup 5_) are apparently considered bonus videos and show up in the list without an extra parameter:
```suggestion
	siteCollector.Visit(URL + "?sort=latest&bonus-video=1")
```

File: pkg/scrape/vrbangers.go (hunk 1 above)
Comment (theRealKLH) [reply pkg/scrape/vrbangers.go:47]: There was some discussion over on discord on "to migrate not to migrate". I opted to pull the migration code I had originally put in. What's the "sane" choice here?

Comment (alexnsfw) [reply pkg/scrape/vrbangers.go:47]: Maybe this?
1. For all scenes, slugify the last component of the URL, with a special case (:vomiting_face:) for ayumis-first-time and save the result. Or since there are just 3... just fix those 3 explicitly.
2. Fetch the list of all scenes from the API (e.g. `/api/content/v1/videos?page=1&type=videos&sort=latest&show_custom_video=1&bonus-video=1&limit=500`).
3. Using values from the JSON, for each scene `update scenes set scene_id = <back 8 of id> where scene_url like '%/<slug>'`.

Also I should probably check out the DIscord...

Comment (theRealKLH) [reply pkg/scrape/vrbangers.go:47]: I'm going to put the migration back in. flush the scenes. My head hurts. If someone else wants to code this, you are more than welcome.  Do we want to be doing a lot of coding in "migrations". Or more than scraping in the scrapers?

Comment (alexnsfw) [reply pkg/scrape/vrbangers.go]: I gave it a shot [here](https://github.com/alexnsfw/xbvr/commit/dfb6f18dabe4c11aa98c89bc54c06687547f7876), it worked great. Never scraped VRBGay or VRBTrans though, so there might be some missing entries in `slugMapping` for those...

Comment (theRealKLH) [reply pkg/scrape/vrbangers.go]: nice. I'll run through it. I have VRBTrans scraped, so it will be a good test.

**Comment by theRealKLH** [comment]
fixes #590

**Comment by theRealKLH** [comment]
should be good to go now.

File: pkg/scrape/vrbangers.go (hunk 1 above)
Comment (theRealKLH) [reply pkg/scrape/vrbangers.go]: good to go

File: pkg/migrations/migrations.go [hunk 3]
```diff
@@ -488,6 +494,87 @@ func Migrate() {
...
+					scene.SceneURL = path.Join(dir, slug) + "/"
+					scene.SceneID = sceneID
+					err = tx.Save(&scene).Error
+					if err != nil {
+						return err
+					}
+				}
+
+				// since scenes have new IDs, we need to re-index them
+				go tasks.SearchIndex()
```
Comment (alexnsfw) [inline pkg/migrations/migrations.go:573]: On second thought, maybe it's not such a good idea to start this in a goroutine? Maybe it shouldn't run concurrently with other migrations?
```suggestion
				tasks.SearchIndex()
```
